package com.cluster.entity;

// Generated 27 Aug, 2014 2:09:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.cluster.dao.BaseDO;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", catalog = "vishumysql")
public class Department extends BaseDO {

	private Integer deptid;
	private String dname;
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Department() {
	}

	public Department(String dname, Set<Employee> employees) {
		this.dname = dname;
		this.employees = employees;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "DEPTID", unique = true, nullable = false)
	public Integer getDeptid() {
		return this.deptid;
	}

	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	@Column(name = "DNAME", length = 30)
	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department",cascade=CascadeType.ALL)
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
